FROM golang:1.24-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o server ./cmd/server

FROM alpine:3.20
WORKDIR /app

COPY --from=builder /app/server ./server
COPY --from=builder /app/internal ./internal
COPY --from=builder /app/media ./media

EXPOSE 8080
CMD ["./server"]
